### ISSUE TITLE
Error Moving Summary Files and Reporting Total Cluster Number

### ISSUE THREAD

**Issue by kbarslan** [fanagislab/EndHiC#10]
Thanks for this amazing tool!

I'm facing a problem while running; it reads the ICED matrix file. Creates and places a summary for all contig end iterations in the respective folders. In the script, it tries to move these files to another directory, but it cannot locate the file (e.g., mv: cannot stat 'X.hicpro.ICE.100000.10.results.summary': No such file or directory). Even though the files are in the Round_A.04.summary_and_merging_results directory. 
I think that's why it cannot report the total cluster number for the ICED matrix, as shown below.

Contig end size: 100000 x 5
Times:  1.5     2.0     2.5     3.0     3.5     4.0     4.5
Raw:    504     505     505     507     509     509     513
Iced:

Contig end size: 100000 x 10
Times:  1.5     2.0     2.5     3.0     3.5     4.0     4.5
Raw:    411     411     412     414     418     426     434
Iced:

I would appreciate any insights into why it is failing to locate and move the summary files correctly. Additionally, suggestions for troubleshooting would be very helpful.

**Comment by fanagislab** [comment]
Please try the testing data first.  And make sure your  data format and directory structure is same with the testing data.



***@***.***
 
From: kbarslan
Date: 2024-02-06 21:43
To: fanagislab/EndHiC
CC: Subscribed
Subject: [fanagislab/EndHiC] Error Moving Summary Files and Reporting Total Cluster Number (Issue #10)
Thanks for this amazing tool!
I'm facing a problem while running; it reads the ICED matrix file. Creates and places a summary for all contig end iterations in the respective folders. In the script, it tries to move these files to another directory, but it cannot locate the file (e.g., mv: cannot stat 'X.hicpro.ICE.100000.10.results.summary': No such file or directory).
I think that's why it cannot report the total cluster number for the ICED matrix, as shown below.
Contig end size: 100000 x 5
Times: 1.5 2.0 2.5 3.0 3.5 4.0 4.5
Raw: 504 505 505 507 509 509 513
Iced:
Contig end size: 100000 x 10
Times: 1.5 2.0 2.5 3.0 3.5 4.0 4.5
Raw: 411 411 412 414 418 426 434
Iced:
I would appreciate any insights into why it is failing to locate and move the summary files correctly. Additionally, suggestions for troubleshooting would be very helpful.

**Comment by kbarslan** [comment]
Thank you for the answer!

The test data is working but I think my issue was my file names. 

Old names;
L1.mapped.pairs.100000.hicpro
L1.mapped.pairs.100000.hicpro.ICE
L1.mapped.pairs.100000.hicpro.bed
ref.genome

Then I tried naming my files as test data file names.

New names;
Fba.contigs.fa
FbaHiC_100000.matrix
FbaHiC_100000_abs.bed
FbaHiC_100000_iced.matrix
 
After that, the analysis ran without any problems.
